### ISSUE TITLE
Namespaced Dev orgs

### ISSUE THREAD

**Issue by Vincent-Ip** [kgalant/PackageBuilder#12]
Hi guys, 

I believe that your package doesn't retrieve custom objects and other items in a Dev org that has been namespaced (as is the case for a App Exchange packaging org).  The resultant package.xml seems to only include Standard object / feilds / etc.  

Perhaps there's a parameter i'm missing to include the default namespace in the package.xml build?

Thanks for all your work on this jar.  SO useful!

**Comment by kgalant** [comment]
Fixed in version 2.3.3 - just committed.

Added -in parameter to permit adding (and downloading) managed package items to the package.xml.
Do note that using this parameter will add all managed package items to the package, not just the InstalledPackage, so e.g. classes from a managed package will appear under the ApexClass type, etc.
