### ISSUE TITLE
InstalledPackage metadata type not pulling

### ISSUE THREAD

**Issue by minal-rama** [kgalant/PackageBuilder#13]
I have both managed and non managed packages installed on my org. When pulling it lists the metadata type see below:

![image](https://user-images.githubusercontent.com/44017973/75882754-76068e80-5e2a-11ea-8447-6e33f540c225.png)

but returns 0 yet I have packages in my org

**Comment by kgalant** [comment]
Fixed in version 2.3.3 - just committed. 

Added -in parameter to permit adding (and downloading) managed package items to the package.xml.
Do note that using this parameter will add all managed package items to the package, not just the InstalledPackage, so e.g. classes from a managed package will appear under the ApexClass type, etc.
